### ISSUE TITLE
GCE admin VM does not have proper permission to pull serviceaccount json

### ISSUE THREAD

**Issue by sapient007** [GoogleCloudPlatform/anthos-samples#119]
GCE admin VM needs service account permission (iam.serviceAccountKeyAdmin) to be able to complete the init.sh script. The script retrieves the service account json via gcloud command. We need to have a variable to set proper account permissions for the GCE instance to have that permission

**Comment by Shabirmean** [comment]
This has been fixed in https://github.com/GoogleCloudPlatform/anthos-samples/pull/120
