### ISSUE TITLE
Enable GPU support for ABM Terraform installation on GCE

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/anthos-samples#12]
The ABM Terraform installation needs GPU support in order to run ML and TensorFlow based GPU workloads. There are two options to do that -

- Terraform Resource
- Terraform Modules (Instance Template needs GPU support)

The example code below works for GCE with NVIDIA Tesla V100 using Terraform Resource: 

```yaml
resource "google_compute_instance" "gpu-vm" {
  count = 1
  name = "gpu-vm"
  machine_type = "n1-standard-4" // 1 CPU 16 Gig of RAM
  zone = "us-west1-a" // Call it from variable "region"
  tags = ["http"]
  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-1604-lts"
      size = 50 // 50 GB Storage
    }
   }
  network_interface {
    network = "default"
      access_config {
        // Ephemeral IP - leaving this block empty will generate a new external IP and assign it to the machine
      }
  }
  guest_accelerator{
    type = "nvidia-tesla-v100" // Type of GPU attahced
    count = 1 // Num of GPU attached
  }
  scheduling{
    on_host_maintenance = "TERMINATE" // Need to terminate GPU on maintenance
  }
}
```

Once we have the GPU enabled we'll be installing the NVIDIA GPU and CUDA drivers.

**Comment by puneith** [comment]
@Shabirmean I've added this issue with Terraform Resource GPU details for reference.

**Comment by Shabirmean** [comment]
The necessary changes suggested above have been submitted and approved to the `instance_template` module from the `terraform-google-vm` repo. [See PR here](https://github.com/GoogleCloudPlatform/anthos-samples/pull/11)

However, keeping this issue open until a release is cut with those changes. [See release PR here](https://github.com/terraform-google-modules/terraform-google-vm/pull/158).

**Comment by puneith** [comment]
@Shabirmean You've updated this PR with GPU support? Sorry I didn't have time to take a look, but we should make sure that the GPU support (if added) should be a switch and can be turned on/off.

**Comment by Shabirmean** [comment]
> @Shabirmean You've updated this PR with GPU support? Sorry I didn't have time to take a look, but we should make sure that the GPU support (if added) should be a switch and can be turned on/off.

I haven't yet added it to the current PR. Waiting for the release branches to cut on the [terraform-google-vm](https://github.com/terraform-google-modules/terraform-google-vm) repo.

Do you think we should include this in the current PR? I can ask the maintainer of that repo to cut a release. He asked me to tell him if we want a release.

**Comment by puneith** [comment]
I'd suggest merge this work. The GPU enhancement can be added on top of it as a separate PR.
