### ISSUE TITLE
Subsequent runs of the TF script for ABM setup with new variables conflict

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#14]
### Issue:
- With the current setup if we run the ABM on GCE TF scripts twice with different cluster names the second one conflicts with the first

### What should happen:
- Subsequent runs with different TF variables should produce 2 different clusters

### Potential fix:
- Prefix the resources with the cluster_name from the variables
- Take in a separate prefix var to use with each resource name specific to a cluster

**Comment by donmccasland** [comment]
Shabir can we get some attention on this OSLO bug?

**Comment by Shabirmean** [comment]
This issue will be fixed by https://github.com/GoogleCloudPlatform/anthos-samples/pull/108

However, the user should note to modify two variables in the [`terraform.tfvars`](https://github.com/GoogleCloudPlatform/anthos-samples/blob/master/anthos-bm-gcp-terraform/terraform.tfvars.sample) file between subsequent runs of the script:
1. abm_cluster_id
2. anthos_service_account_name
