### ISSUE TITLE
Enable nested virtualization support for ABM Terraform installation on GCE

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/anthos-samples#211]
Hardware virtualization provides better performance than software emulation when using [Anthos VM Runtime](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/vm-workloads) on ABM.   On GCE [nested virtualization](https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling) can be enabled in TF with the `enable_nested_virtualization` parameter.

**Comment by NimJay** [comment]
@Shabirmean (ABM DPE), I'm tagging you here in case you'd like to change the priority of this ticket.
I've set it to `p3` since it's a performance improvement — not a bug or pressing feature requirement.

**Comment by Shabirmean** [comment]
Thank you @NimJay . Yeah I think `p3` looks good here.
