### ISSUE TITLE
Add a new folder for hosting Anthos on VMware specific resources

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#249]
### Description
- We don't have a specific area for hosting A4VMWare specific resources
- So we need to a new directory for this and enable pulling these material into the docs via region tags

**Comment by bourgeoisor** [comment]
@Shabirmean is this still relevant?

**Comment by Shabirmean** [comment]
It is. But doesn't need explicit tracking until we allocate some resources to do this. So closing this
