### ISSUE TITLE
feat: [anthos-bm-gcp-terraform] cluster/resources randomized suffix

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/anthos-samples#262]
To prevent conflicts with repeated usage, a randomized suffix could be automatically attached to the cluster name/resources.

Would also workaround #261

**Comment by bourgeoisor** [comment]
@apeabody is this issue still relevant / active?

**Comment by apeabody** [comment]
Hi @bourgeoisor! - I would say this is still *relevant*, however baring an active requirement from anyone else I think we can close out.  #269 addressed my requirement sufficiently.
