### ISSUE TITLE
feat: add [anthos-bm-gcp-terraform] multiple instantiations

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/anthos-samples#296]
As a user I would like to deploy multiple copies of [anthos-bm-gcp-terraform] in a single project.  Currently this isn't possible due to a few static resource names leading to collisions.  For example: https://github.com/GoogleCloudPlatform/anthos-samples/blob/2799fd5d33614fdf09008e4c5c04c63772891f46/anthos-bm-gcp-terraform/main.tf#L44

**Comment by NimJay** [comment]
@apeabody First off, thanks for all the work you've been doing on `anthos-samples`.

Could you please elaborate (in the description of this GitHub Issue)? :)
Thanks!
