### ISSUE TITLE
[Anthos-multi-cloud]volume_kms_key - customer managed key not getting created in KMS module

### ISSUE THREAD

**Issue by jayesh-bhandari** [GoogleCloudPlatform/anthos-samples#303]
In anthos-multi-cloud/AWS/modules/anthos_cluster/main.tf , volume_kms_key kms key is used to encrypt EC2 volumes.
However the KMS module does not create volume_kms_key. Instead volume_kms_key is assigned a null value.

Though it works perfectly for now as volume_kms_key with null value creates a aws managed key. However it will be good to have customer managed kms key to encrypt the volumes as well.

**Comment by Shabirmean** [comment]
Tagging @GoogleCloudPlatform/anthos-multicloud as owners of the sample

**Comment by jiefenghe** [comment]
I think we can mark it as fixed now
