### ISSUE TITLE
Reduce Ansible installation time by bundling static steps into the VM image

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#310]
### What? 

As per the current state of the Ansible installation scripts the process takes ***~35 minutes*** to complete. We can reduce this time by bundling some of the static steps in the Ansible scripts **(that does not change with the _host_vars_)** into a VM image.

This can make the quick start experience much better by reducing the time it takes to reach completion.

#### Notes:
- Everything up to `abm-install` can be packaged into an image
- The image needs to be available to both **GCE** and **physical machines**
- Explore using [Packer Qemu builder](https://www.packer.io/docs/builders/qemu) to create the images
- We can try building the image for QEMU in GCP and converting it

**Comment by Shabirmean** [comment]
This is open following [this issue](https://github.com/GoogleCloudPlatform/point-of-sale/issues/15) which was created when the anthos-bm-edge-deployment sample was in the point-of-sale repo

**Comment by bourgeoisor** [comment]
@Shabirmean is this still relevant?

**Comment by Shabirmean** [comment]
This is still an important milestone for the anthos-on-edge deployment. However, this is not within the DEE priorities given the recent org changes. So we can close this issue for now and check for updates in the upstream repo. We can port those updates here where and when it makes sense
