### ISSUE TITLE
Re-write the Ansible scripts to install Config Sync via the gcloud method 

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#311]
### What?
- The current scripts in the repository uses the [manual installation method](https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl) for Config Sync using **kubectl** which is unsupported
- As a result this can lead to bugs that can be hard to track: [b/200555955](http://b/200555955) ***(internal link)***
- Thus, we would to re-write the ACM installation in the Ansible scripts to use the [`gcloud` based method](https://cloud.google.com/anthos-config-management/docs/how-to/installing)

**Comment by Shabirmean** [comment]
This is open following [this issue](https://github.com/GoogleCloudPlatform/point-of-sale/issues/13) which was created when the anthos-bm-edge-deployment sample was in the point-of-sale repo

**Comment by ahrarmonsur** [comment]
@Shabirmean any updates on the progress of addressing this issue?

**Comment by Shabirmean** [comment]
PR #377 should address this issue. However, it is kept pending since we need a green flag from some internal stakeholders!

**Comment by NimJay** [comment]
@Shabirmean thanks for the clarification in your previous comment.
Now that #377 is merged, could we close this issue?

**Comment by Shabirmean** [comment]
@NimJay - Yes, we are good to close this issue. Thank you for checking this!
