### ISSUE TITLE
Fix Ansible script warnings

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#312]
### What?

As reported by some [friction-logs](http://go/obourgeois-friction-abm-edge-usecase) there some `warnings` during the ansible run. These are related to a deprecation notice for `Python2.7` starting from `Ansible 2.12`. See an example warning below:

```sh
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with 
Ansible 2.12. Current version: 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]. This feature will 
be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```
```sh
/home/user/.local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: 
CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is 
now deprecated in cryptography,  and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
```

We need to fix these warnings.

**See attachment for an example of log output of the execution of these ansible scripts.**

[abm-edge-ansible.log](https://github.com/GoogleCloudPlatform/anthos-edge-usecases/files/7297457/abm-edge-ansible.log)

**Comment by Shabirmean** [comment]
This issue was openned following https://github.com/GoogleCloudPlatform/point-of-sale/issues/14, since the anthos-bm-edge-deployment sample was moved from that repo to here

**Comment by bourgeoisor** [comment]
@Shabirmean is this issue still relevant?
