### ISSUE TITLE
service account keys sh 

### ISSUE THREAD

**Issue by xtineskim** [GoogleCloudPlatform/anthos-samples#353]
The script that we use for generating new service account keys (that expire every 90 days) does not work as expected. The sa-key.json cannot be generated. The only work around we have is going through the console.
I believe it may be a perms issue, but not 100% sure

**Comment by NimJay** [comment]
**Updating to cool out-of-SLO list:**

Could you clarify what you mean by "service account keys"?
Are these "service account keys" related to some CI pipeline run by pull-requests?
(Sorry, I'm unfamiliar with most of the CI in this repo.)
