### ISSUE TITLE
The anthos-bm-edge-deployment sample doesn't work with 1.12 ABM

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#376]
### Description:
- The sample for rolling out ABM to edge clusters inside [anthos-bm-edge-deployment](https://github.com/GoogleCloudPlatform/anthos-samples/tree/main/anthos-bm-edge-deployment) folder doesn't work as expected when the ABM and ACM versions are updated to 1.12

**Comment by ahrarmonsur** [comment]
@Shabirmean do you have an update on this issue? Do you have more details on how exactly it is not working as expected?

Additionally, one small correction:
The link in the description has a dead link. Should be
https://github.com/GoogleCloudPlatform/anthos-samples/tree/main/anthos-bm-edge-deployment

**Comment by Shabirmean** [comment]
@ahrarmonsur this was reported by an OPM. I don't have access to the specific errors; I opened this as a tracking bug for what was reported. 

This should be fixed in the linked PR #377. We are waiting on the that PR since we need a green flag ✅ from some internal stakeholders.

**Comment by mathieu-benoit** [comment]
Should we ask for an update on this https://github.com/GoogleCloudPlatform/anthos-samples/pull/377#issuecomment-1249594893?

**Comment by Shabirmean** [comment]
@mathieu-benoit - I will speak to Mike and see what's the status!
