### ISSUE TITLE
No valid credentials for AWS provider 

### ISSUE THREAD

**Issue by thunderhill** [GoogleCloudPlatform/anthos-samples#401]
Getting this error.
$ terraform apply
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 26, in provider "aws":
│   26: provider "aws" {
│
╵

**Comment by ahrarmonsur** [comment]
@thunderhill thank you for logging this issue. Am I correct that you were attempting to deploy the following sample?
https://github.com/GoogleCloudPlatform/anthos-samples/tree/main/anthos-multi-cloud/AWS

@Shabirmean  would you please assist? Thank you.

**Comment by ckim328** [comment]
and also how are providing your credentials?

**Comment by Shabirmean** [comment]
@GoogleCloudPlatform/anthos-multicloud - Can you PTAL. Seems like the error was from the `AWS/Multicloud` sample.

**Comment by bourgeoisor** [comment]
@bkauf is this something you can take a look at?

**Comment by minherz** [comment]
Closing it due to lack of communication. Feel free to reopen if the issue happens again or you have new information.
