### ISSUE TITLE
Terraform version is outdated 

### ISSUE THREAD

**Issue by xtineskim** [GoogleCloudPlatform/anthos-samples#413]
The terraform version that comes with cloudshell, and the TF version in the `anthos-bm-gcp-terraform` sample only allows for versions less than `1.2`.
Should update, or at least document a workaround

https://releases.hashicorp.com/terraform/

**Comment by apeabody** [comment]
We also have an environment that requires a newer version of TF, 1.3.x in particular.  If anthos-samples could be updated soon to support TF 1.3.x it would be greatly appreciated.

@Shabirmean

**Comment by apeabody** [comment]
@zhuchenwang
