### ISSUE TITLE
Persist vxlan interface after gce vm reboot

### ISSUE THREAD

**Issue by antoniordz96** [GoogleCloudPlatform/anthos-samples#43]
## Issue
With the current setup if we run the ABM on GCE TF and reboot one of the gce vms, the vxlan interface used by the VM is wiped. 

## What should happen:
VXLAN interface created by terraform should persist after reboot. 

## Potential fix:
If you use ifconfig to configure network interfaces, the changes will be lost after reboot. To make your changes persistent, you need to modify configuration files like /etc/network/interfaces.

**Comment by Shabirmean** [comment]
Refer _(Optional)_ section of [this step](https://docs.google.com/document/d/19gBotDBFoyNcs1jev_IZ8mCcTIxgyLH9BEe4cqizmis/edit#heading=h.9wykpee7qym2) in [go/anthos-bm-gce-vxlan](http://go/anthos-bm-gce-vxlan) **[internal]** doc

**Comment by bourgeoisor** [comment]
@Shabirmean is this issue still relevant?

**Comment by Shabirmean** [comment]
Yes this is still relevant.

**Comment by minherz** [comment]
@Shabirmean please select one type for this issue.
