### ISSUE TITLE
Update the release process to change the tf module versions in versions.tf

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#45]
#### Which sample?
- anthos-bm-gcp-terraform

#### Description
- The release process for the sample is based on the [release-please](https://github.com/googleapis/release-please#release-please) bot. Currently we are using the `terraform-module` [release type](https://github.com/googleapis/release-please#release-please) which is based off of the [go/blueprints](go/blueprints) project
- However, we should upgrade this to add our own release type to achieve the following:
    - Upon release the versions of the other terraform modules under the `provider_meta` definition in the `versions.tf` file shall be updated to the correct versions used for each module during time of the release

#### Potential fix
- Add a new [`releaser` and a `updater` ](https://github.com/googleapis/release-please#adding-additional-release-types) that extends the existing `terraform-module` type to the `release-please` repo 
- Use this new type in our release configs in the anthos-samples repo

#### Useful:
- Existing terraform-module [releaser](https://github.com/googleapis/release-please/blob/master/src/releasers/terraform-module.ts)
- Existing terraform-module [updater](https://github.com/googleapis/release-please/tree/master/src/updaters/terraform)
- Release [automation bot](https://github.com/googleapis/repo-automation-bots/tree/master/packages/release-please) wrapper around [release-please](https://github.com/googleapis/release-please) npm package
- All [automation bots](https://github.com/googleapis/repo-automation-bots)

#### Considerations about using the `provider_meta` field to maintain dependencies:
- *Pros:* All dependency information is maintained in the `versions.tf` file as a natural place where someone would look at
- *Cons:* If the definition and usage of `provider_meta` tag changes then the releaser would break. Thus, ideally it might be useful to store this information in a different file (e.g. `dependency_matrix.txt`)

**Comment by bharathkkb** [comment]
@Shabirmean 
> Upon release the versions of the other terraform modules under the provider_meta definition in the versions.tf

Why are the other Terraform modules being tracked in provider_meta?

**Comment by Shabirmean** [comment]
> @Shabirmean
> 
> > Upon release the versions of the other terraform modules under the provider_meta definition in the versions.tf
> 
> Why are the other Terraform modules being tracked in provider_meta?

As discussed offline about the reasoning for using `provider_meta` and the complexities it can introduced, i have updated the issue about those considerations. So that's something that will have to be thought about

**Comment by bourgeoisor** [comment]
@Shabirmean is this issue still relevant?

**Comment by Shabirmean** [comment]
I think this has been open for too long and the current priorities doesn't allow planning on this. So let's close this and come bck if we need to address it
