### ISSUE TITLE
logging filter and throttling

### ISSUE THREAD

**Issue by arctiqaurora** [GoogleCloudPlatform/anthos-samples#5]
Are there ways to add throttle or extra filters to limit the network consumption? 

I tried to add throttling to fluentd config map but the plugin is not available.

**Comment by rsgowman** [comment]
Hi @arctiqaurora,

Is this still an issue? If so, is this using the 'attached-logging-monitoring'
samples from within this repo?

Assuming yes to both, there's a few things that might work for you:

1. Filtering. This could be done at either the aggregator (fluentd) or forwarder
   (flutent bit) level. The forwarder might make more sense. To do so, you could
   add a fluent bit filter to simply drop some of the logs. eg, I've added the
   following filter to get rid of all logs from my calico app:

   ```
   [FILTER]
       name grep
       match *
       exclude kubernetes['container_name'] calico-node
   ```

   (That file is in the configmap/stackdriver-log-forwarder-config configmap,
   under filter-kubernetes.conf)

2. Throttling. Again, this can be done at either level, though in this case, it
   probably makes more sense at the aggregator level. Unfortunately, the image
   that's being used doesn't include the throttle plugin (as you've noted). You
   could create an image that does and switch to it, or you could add throttling
   at the forwarder level. eg, editing that same configmap again and adding:

   ```
   [FILTER]
       name throttle
       match *
       rate 1
       window 5
       interval 1s
   ```

   This would throttle each node to 1 log message per second (on average). Extra
   messages would be dropped. (The total log messages per second uploaded 
   would depend on the number of nodes in the cluster.)

   Although it would depend on the use case, I'd generally prefer to go with the
   filtering route; at least that way I get to choose what gets dropped rather
   than risking an important log message disappearing when the system is busy.

**Comment by rsgowman** [comment]
Closing as obsolete. But please feel free to re-open if this is still an issue.
