### ISSUE TITLE
Windows node forwarder configuration

### ISSUE THREAD

**Issue by roger-reed** [GoogleCloudPlatform/anthos-samples#6]
We are using Anthos Attached in a cluster with Windows nodes.  fluent-bit is not an option for Windows,  however there is a fluentd image for Windows.  Could you please provide a fluentd configuration to forward to your Stackdriver aggregator?  Or could you provide another method to forward logs from Windows nodes?

**Comment by igorpeshansky** [comment]
Note that fluent-bit *is* available on Windows: https://docs.fluentbit.io/manual/installation/windows. The fluent-bit build used for Anthos may not be, however.
