### ISSUE TITLE
Unrecoverable error sending samples to remote storage

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/anthos-samples#9]
I'm on AKS 1.18.14, and when running `kubectl logs stackdriver-prometheus-k8s-0 -n kube-system stackdriver-prometheus-sidecar` like recommended [here](https://cloud.google.com/anthos/attached-clusters/docs/logging-monitoring#installing_the_monitoring_agent) I'm seeing the expected info:
```
level=info ts=2021-03-15T03:41:33.933Z caller=main.go:598 msg="Web server started"
level=info ts=2021-03-15T03:41:33.933Z caller=main.go:579 msg="Stackdriver client started"
```
But I'm also seeing a lot of warnings like this:
```
level=warn ts=2021-03-15T03:42:37.427Z caller=queue_manager.go:534 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.: timeSeries[0-3]"
level=warn ts=2021-03-15T03:43:10.559Z caller=queue_manager.go:534 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.: timeSeries[85-87,91,92,98,100,103,105-156]; Unknown metric: kubernetes.io/anthos/coredns_cache_size: timeSeries[88,89]; Unknown metric: kubernetes.io/anthos/coredns_dns_request_count_total: timeSeries[90]; Unknown metric: kubernetes.io/anthos/coredns_dns_request_type_count_total: timeSeries[93-95]; Unknown metric: kubernetes.io/anthos/coredns_dns_response_rcode_count_total: timeSeries[96,97]; Unknown metric: kubernetes.io/anthos/coredns_forward_request_count_total: timeSeries[99]; Unknown metric: kubernetes.io/anthos/coredns_forward_response_rcode_count_total: timeSeries[101,102]; Unknown metric: kubernetes.io/anthos/coredns_panic_count_total: timeSeries[104]"
```
Is it expected? Am I missing something? Or is it an issue?

Thanks.

**Comment by rsgowman** [comment]
This was resolved internally, but for anyone following along, the tl;dr is:

```
One or more points were written more frequently than the maximum sampling period configured for the metric
```
These are safe to ignore.

```
Unknown metric: ...coredns...
```

This implies that these metrics haven't been added to the internal allowlist, so they wouldn't be uploaded to stackdriver. Other metrics would be unaffected. However, we've since added these to our allowlist, so this issue should be resolved.

**Comment by rsgowman** [comment]
> ```
> Unknown metric: ...coredns...
> ```
> 
> This implies that these metrics haven't been added to the internal allowlist, so they wouldn't be uploaded to stackdriver. Other metrics would be unaffected. However, we've since added these to our allowlist, so this issue should be resolved.

Correction: We now capture some, but not all, coredns metrics. These ones aren't captured.
