### ISSUE TITLE
Swap CFT test framework for new blueprints test framework

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/anthos-samples#91]
Tracking issue for migrating from CFT test framework to our new [blueprints test framework](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/infra/blueprint-test). Both sets of tests can co exist as we migrate.

**Comment by bourgeoisor** [comment]
@bharathkkb is this issue still active?

**Comment by bourgeoisor** [comment]
Closing due to lack of response, feel free to reopen if still relevant!

**Comment by bharathkkb** [comment]
@bourgeoisor sorry I missed the previous ping but yes we should migrate all tests similar to https://github.com/GoogleCloudPlatform/anthos-samples/pull/92
