### ISSUE TITLE
The gke.googleapis.com labels are set on the wrong level for systemd

### ISSUE THREAD

**Issue by jiwang576** [GoogleCloudPlatform/anthos-samples#98]
There should be an extra nest plugin to nest them under "logging.googleapis.com". Maybe we should consider move it to filter-kubernetes.conf so it can be effective for all included files.

https://github.com/GoogleCloudPlatform/anthos-samples/blob/1da0132772f43655ef97e54841de755f143b394d/aws-logging-monitoring/logging/forwarder.yaml#L203

``` 
[FILTER]
        # https://docs.fluentbit.io/manual/filter/nest
        Name    nest
        Match   *
        Operation nest
        Wildcard gke.googleapis.com*
        Nest_under logging.googleapis.com/labels
```

**Comment by Shabirmean** [comment]
@erain @rsgowman @leonzz - any thoughts on this issue?
